version: 2
jobs:
   build:
     docker:
       - image: lukaszkostka/qt5:debian_buster
     steps:
       - checkout
       - run:
          name: Run cmake
          command: >
            cmake
            -H.
            -GNinja
            -Bbuild
       - run:
          name: Build
          command: ninja -C build
