defaults: &defaults
  steps:
   - checkout
   - run:
       name: Run cmake
       command: >
         cmake
         -H.
         -GNinja
         -Bbuild
   - run:
       name: Build
       command: ninja -C build

version: 2
jobs:
   build_debian_buster:
     docker:
       - image: lukaszkostka/qt5:debian_buster
     <<: *defaults
   build_debian_stretch:
     docker:
       - image: lukaszkostka/qt5:debian_buster
     <<: *defaults
   build_macos:
     macos:
       xcode: "9.0"
     steps:
       - checkout
       - run:
           name: Install requirements
           command: >
             brew install
             qt5
             cmake
             ninja
       - run:
           name: Run cmake
           command: >
             cmake
             -H.
             -GNinja
             -Bbuild
       - run:
           name: Build
           command: ninja -C build

workflows:
  version: 2
  build:
    jobs:
      - build_macos
      - build_debian_buster
      - build_debian_stretch
